apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bestbuy
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bestbuy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: nada0038/order-service-bestbuy:latest
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "1.0.0"
        - name: ORDER_QUEUE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ORDER_QUEUE_HOSTNAME
        - name: ORDER_QUEUE_PORT
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ORDER_QUEUE_PORT
        - name: ORDER_QUEUE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username
        - name: ORDER_QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: ORDER_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ORDER_QUEUE_NAME
        - name: ORDER_QUEUE_RECONNECT_LIMIT
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ORDER_QUEUE_RECONNECT_LIMIT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

