apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  namespace: bestbuy
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: makeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
  namespace: bestbuy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
      - name: makeline-service
        image: nada0038/makeline-service-bestbuy:latest

        ports:
        - containerPort: 3001

        env:
        # ✅ Pull Mongo username from secret
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username

        # ✅ Pull Mongo password from secret
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password

        # ✅ Build full authenticated Mongo connection string
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/bestbuy?authSource=admin"

        # ✅ RabbitMQ (already confirmed working)
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: host

        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username

        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password

        - name: RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: makeline-config
              key: queue_name

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
