apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  namespace: bestbuy
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: makeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
  namespace: bestbuy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
      - name: makeline-service
        image: nada0038/makeline-service-bestbuy:latest

        ports:
        - containerPort: 3001

        env:
        # MongoDB Configuration (makeline service expects these names)
        - name: ORDER_DB_URI
          value: "mongodb://mongodb:27017"
        
        - name: ORDER_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: makeline-service-config
              key: ORDER_DB_NAME

        - name: ORDER_DB_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: makeline-service-config
              key: ORDER_DB_COLLECTION_NAME

        # MongoDB Username and Password (for authentication)
        - name: ORDER_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username

        - name: ORDER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password

        # RabbitMQ Configuration (makeline service expects these names)
        - name: ORDER_QUEUE_URI
          valueFrom:
            configMapKeyRef:
              name: makeline-service-config
              key: ORDER_QUEUE_URI

        - name: ORDER_QUEUE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: username

        - name: ORDER_QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password

        - name: ORDER_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: makeline-service-config
              key: ORDER_QUEUE_NAME

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
